In [1]:
#!/usr/bin/env python

import os
import torch
from PIL import Image
import numpy as np
import ipywidgets as widgets
from ipywidgets import interact, interactive, fixed, interact_manual
from torch.utils.data.dataloader import default_collate
import matplotlib.pyplot as plt
from tqdm import tqdm

from core.dataset import Rescale, TransferTensorDict, EpicClasses
from core.tools import initialize, visualize

torch.multiprocessing.set_sharing_strategy("file_system")

In [2]:
cfg, model, dataset, epic_classes, device = initialize("config/config_vis.yaml")
data_loader = torch.utils.data.DataLoader(
        dataset,
        batch_size=24,
        shuffle=False,
        num_workers=8,
    )

Initializing model...
Model initialized with imagenet weights
Freezing the batchnorms of Base Model RGB except first or new layers.
Model initialized with imagenet weights
Freezing the batchnorms of Base Model Audio except first or new layers.
Model initialized.
----------------------------------------------------------
Loading pre-trained weights /media/data/tridiv/epic/tbn_weights/prior_kl/unseen/epic_tbn_bninception_RGB_Audio.pth...
Done.
----------------------------------------------------------
Reading list of test videos...
Done.
----------------------------------------------------------
Creating the dataset using annotations/EPIC_train_action_labels.csv...
Done.
----------------------------------------------------------


In [3]:
%matplotlib inline
interact(visualize, cfg=fixed(cfg), model=fixed(model), dataset=fixed(dataset), index=widgets.IntSlider(min=1, max=len(dataset), step=1, value=0, continuous_update=False), epic_classes=fixed(epic_classes), device=fixed(device))

interactive(children=(IntSlider(value=1, continuous_update=False, description='index', max=5793, min=1), Outpu…

<function core.tools.vis.visualize(cfg, model, dataset, index, epic_classes, device)>

In [26]:
# entropies = torch.stack(entropy_list)
# sorted_indices = entropies.topk(entropies.shape[0]).indices
# sorted_indices
a = torch.softmax(torch.rand(25), dim=0)
m = a.clone().detach()
m[m >= 0.04] = 1
m[m < 0.04] = 0
l = (a * (1 - m)) - (a * m)

(tensor([0.0311, 0.0260, 0.0515, 0.0460, 0.0475, 0.0212, 0.0491, 0.0459, 0.0530,
         0.0239, 0.0329, 0.0373, 0.0429, 0.0481, 0.0538, 0.0319, 0.0234, 0.0407,
         0.0385, 0.0467, 0.0263, 0.0425, 0.0457, 0.0539, 0.0404]),
 tensor([0.0000, 0.0000, 0.0515, 0.0460, 0.0475, 0.0000, 0.0491, 0.0459, 0.0530,
         0.0000, 0.0000, 0.0000, 0.0429, 0.0481, 0.0538, 0.0000, 0.0000, 0.0407,
         0.0000, 0.0467, 0.0000, 0.0425, 0.0457, 0.0539, 0.0404]),
 tensor([ 0.0311,  0.0260, -0.0515, -0.0460, -0.0475,  0.0212, -0.0491, -0.0459,
         -0.0530,  0.0239,  0.0329,  0.0373, -0.0429, -0.0481, -0.0538,  0.0319,
          0.0234, -0.0407,  0.0385, -0.0467,  0.0263, -0.0425, -0.0457, -0.0539,
         -0.0404]))